name: Proof CI (A2H+S1+S2 strict)
on:
push:
branches: [ "main" ]
pull_request:
branches: [ "main" ]
jobs:
proof:
runs-on: ubuntu-latest
steps:
uses: actions/checkout@v4
uses: actions/setup-python@v5
with:
python-version: "3.11"
run: echo "Proof CI alive"
