name: Proof CI (A2H+S1+S2 strict)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: proof-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  proof:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f spec_pack/requirements.txt ]; then
          pip install -r spec_pack/requirements.txt
          else
          pip install --quiet pyyaml
          fi
          
      - name: A2H check
        run: python3 spec_pack/tools/a2h_compile.py --check

      - name: S1 checks
        run: python3 spec_pack/tools/run_s1.py

      - name: S2 inject
        run: python3 spec_pack/tools/s2_contradiction.py

      - name: S2 check
        run: python3 spec_pack/tools/s2_check.py
