name: S1
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  s1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # ÉTAPE AJOUTÉE PAR COPILOT - C'EST LA CORRECTION
      - name: Install dependencies
        run: pip install pyyaml

      - name: Run S1
        run: python3 spec_pack/tools/run_s1.py
