`yaml
  name: S1

  on:
    push:
    pull_request:

  jobs:
    s1:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: pip install -r spec_pack/requirements.txt

        - name: Run S1 checks
          run: python3 spec_pack/tools/run_s1.py
  `
